### ISSUE TITLE
reliablity of sink

### ISSUE THREAD

**Issue by alexhumphreys** [intel/wds#134]
Hey there,

I'm testing out wds on Ubuntu 14.10 with wpa_supplicant 2.4, connmand 1.30, and an Onkyo UWF-1 wifi adaptor (chipset i believe is AR9271), with a Nexus 10 tablet (Android 5.1.1). I'm just wondering, following the instructions in the README [here](https://github.com/01org/wds#testing-wds-sink-with-an-android-device-eg-nexus-5), I manage to connect and cast about 30% or 40% of the time. 

I get a variety of failure modes:
- stays stuck on connecting
- my sink disappears from the cast screen list and reappears
- gets stuck in an appearing -> connecting -> appearing -> connecting loop
- after accepting the connection in connmanctl an invite appears back on the android tablet saying my host wants to connect to it. No connection is made after.

I've tried with the same tablet and a Microsoft Wireless Display adapter and it seems to connect every time so I don't think it's on the android side.

So, just wondering, what reliability do ye get? And what could you suggest changing in my setup to improve reliability? Let me know if you have any questions or want output from anything.

(Possibly each of the list above should be their own issue, but I just wanted to make sure it isn't my setup first)

Cheers,
Alex.

**Comment by kanavin** [comment]
It may be that something is buggy in adapter drivers, because random failures often are a sign of hardware/driver issue. Are you able to try with a different adapter?

**Comment by alexhumphreys** [comment]
Thanks for getting back to me. I can't check with a different adapter right now I'm afraid, but I should be able to in the new year.
