### ISSUE TITLE
what files should i edit for enabling p2p support 

### ISSUE THREAD

**Issue by visbs** [intel/wds#184]
1. i know there is a thread that already talked about this but still i need a detailed explaination of the wpa_supplicant.conf editing (i.e contents  of wpa_supplicant.conf )
as of now connmanctl gives me 
connmanctl> technologies
/net/connman/technology/wifi
  Name = WiFi
  Type = wifi
  Powered = False
  Connected = False
  Tethering = False
/net/connman/technology/ethernet
  Name = Wired
  Type = ethernet
  Powered = True
  Connected = True
  Tethering = False
as there is no p2p support i know i have to do some changes to wpa_supplicant.conf 

my wpa_supplicant.conf.

ctrl_interface=/var/run/wpa_supplicant

network={
	ssid="example wpa-psk network"
	key_mgmt=WPA-PSK
	proto=WPA
	pairwise=TKIP
	group=TKIP
	psk="secret passphrase"
}
2. where should i un-comment the CONFIG_P2P=y and etc  in the .config file(i.e which file ) 

i am stuck in this from past 20 days plz help :(

**Comment by uqmessias** [comment]
@visbs, did you find a way to enable it? I'm having the same issue here

**Comment by visbs** [comment]
@uqmessias  yes i did u just need to compile your wpa_supplicant with p2p support .
https://www.linuxtopic.com/2017/08/compile-wpasupplicant-ubuntu.html
The above link gives you the steps to do the same. But copy the following 
cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
CONFIG_WIFI_DISPLAY=y
CONFIG_AP=y
CONFIG_P2P=y
CFLAGS += -I/usr/include/libnl3
EOF

My /etc/wpa_supplicant/abcd.conf looks like,

ctrl_interface=DIR=/var/run/wpa_supplicant
device_name=my_device
device_type=1-0050F204-1
ap_scan=1
config_methods=pbc

**Comment by uqmessias** [comment]
I'll try it later at home :)
@visbs , thank you for taking the time to answer me.
