### ISSUE TITLE
p2p: implement a "sir yes sir" connman agent

### ISSUE THREAD

**Issue by jku** [intel/wds#19]
We should a have a connman agent that accepts every connection request it gets (or optionally  gets user input)

**Comment by jku** [comment]
As mentioned in last meeting, I now don't think we should do this -- at least not as part of wysiwidi proper: the agent should be a system level thing. 

A script to ease testing might still be useful.

**Comment by jku** [comment]
I have a patch for connman that adds a new agent mode "auto" to connmanctl: it will auto-accept peer authorization requests without input parameters (typical when running sink) and requests with WPS parameter (these happen e.g. when using our source to connect to a peer). This means there's normally no need to pay attention to connmanctl anymore while testing.

https://github.com/jku/connman/tree/agent-auto

I'll send this upstream once I think it works as expected.

**Comment by jku** [comment]
So the patch is good AFAICT. I sent it to connman list but it does not look like they'll take it.

**Comment by vipere** [comment]
I'm trying out wysiwidi, and noticed this issue.
Can I use the connman version in your agent-auto branch, or is it too old? (the recommended version in the readme is Jan 26th 2015 and later)

**Comment by jku** [comment]
@vipere oh you should use the newer connman -- the DHCP fixes can be crucial depending on the other device you're testing with. 

Thanks for the comment though, I'll update the branch (but it's a single commit in a part of code that is rarely touched: it should be very easy to rebase that commit on top of connman master any time you want).

**Comment by jku** [comment]
Ok, the agent-auto branch is now based on current connman master (it's force pushed because I want to keep the branch as one clean commit on top of upstream connman). I've not had a chance to test it yet but it should be fine. FYI: You may need to re-run connmans 'bootstrap-configure' again if the compile fails: it's not always smart enough to figure config changes when checking out different versions.

Related: there was a connman release a week ago so we can start requiring connman 1.28 now.

**Comment by andybeg** [comment]
Hi. Can you explain how i can use you branch, now i get connman via
git clone -b agent-auto https://github.com/jku/connman.git
and to activate miracast still need agent verification

**Comment by jku** [comment]
It's been a while... If I remember correctly you start connmanctl as normal, enable wifi and p2p, then run "agent auto". It should now auto-accept every connection request from a remote P2P device. Obviously this only works for "yes/no" questions, not if the remote device asks for a PIN.

Just to make sure "agent auto" is a debugging helper, nothing more. An actual production agent should probably be part of the operating system UI...

**Comment by andybeg** [comment]
yes it work now. Is any way to start auto accepting miracast connection without enterring into connmanctl (may be some console cmd)?
i make miracast on freescale imx6 processor and need to start it full functional without keyboard and human access.

**Comment by jku** [comment]
For production use you really should write an actual connman agent (A fairly simple D-Bus service that implements the agent API) that makes the policy decisions about what connections to accept.

A simple agent (e.g. one that supports just WPS pushbutton mode) shouldn't be more than a couple of dozen lines of python.

**Comment by jku** [comment]
I'm cleaning up my github issues: This one is unlikely to move forward after five years: I'm closing. I'll leave the branch in place in case someone wants to look at it for inspiration
